// Windissect recovered ABI metadata — DO NOT EDIT.
// Portable across C++17, C++20, C++23, and C++26 draft modes.
#pragma once
#include <cstddef>
#include <cstdint>

namespace windissect_abi {
struct TypeLayout { const char* name; std::uint64_t size; const char* kind; };
struct FieldLayout { const char* owner; const char* name; std::uint32_t type_index; std::uint64_t offset; bool is_static; };
struct FieldObservation { const char* owner; const char* suggested_name; std::uint64_t offset; std::uint32_t width; const char* access; std::uint32_t evidence_rva; const char* evidence_symbol; const char* confidence; };
struct BaseLayout { const char* derived; const char* base; std::int64_t offset; bool is_virtual; const char* evidence; const char* confidence; };
struct VTableLayout { const char* name; std::uint32_t rva; std::uint32_t slots; const char* evidence; const char* confidence; };
struct VTableSlotLayout { std::uint32_t table_rva; std::uint32_t slot; std::uint32_t target_rva; const char* target_id; const char* target_name; bool ambiguous; std::int32_t this_adjustment; };

inline constexpr TypeLayout types[] = {
    {"Microsoft::WRL::ActivationFactory<struct Microsoft::WRL::Implements<class Microsoft::WRL::FtmBase, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics>, class Microsoft::WRL::Details::Nil, class Microsoft::WRL::Details::Nil, 0>", 0ULL, "layout-evidence"},
    {"Microsoft::WRL::ComPtr<class Windows::System::UserProfile::DiagnosticsSettings>", 0ULL, "layout-evidence"},
    {"Microsoft::WRL::Details", 0ULL, "layout-evidence"},
    {"Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<13>, 0, struct IActivationFactory, struct Microsoft::WRL::Implements<class Microsoft::WRL::FtmBase, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics>, class Microsoft::WRL::Details::Nil, class Microsoft::WRL::Details::Nil, class Microsoft::WRL::Details::Nil>", 0ULL, "layout-evidence"},
    {"Microsoft::WRL::Details::MakeAllocator<class Windows::System::UserProfile::DiagnosticsSettings>", 0ULL, "layout-evidence"},
    {"Microsoft::WRL::Details::ModuleBase", 0ULL, "layout-evidence"},
    {"Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::System::UserProfile::IDiagnosticsSettings>", 0ULL, "layout-evidence"},
    {"Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<2>, 1, 0, 0, struct IWeakReference>", 0ULL, "layout-evidence"},
    {"Microsoft::WRL::Details::WeakReferenceImpl", 0ULL, "layout-evidence"},
    {"Microsoft::WRL::FtmBase", 0ULL, "layout-evidence"},
    {"Microsoft::WRL::Module<1, class Microsoft::WRL::Details::DefaultModule<1> >", 0ULL, "layout-evidence"},
    {"Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<2>, struct IWeakReference>", 0ULL, "layout-evidence"},
    {"Microsoft::WRL::RuntimeClass<struct Windows::System::UserProfile::IDiagnosticsSettings>", 0ULL, "layout-evidence"},
    {"Microsoft::WRL::Wrappers::HString", 0ULL, "layout-evidence"},
    {"Windows::System::UserProfile::DiagnosticsSettings", 0ULL, "layout-evidence"},
    {"Windows::System::UserProfile::DiagnosticsSettingsFactory", 0ULL, "layout-evidence"},
    {"exception", 0ULL, "layout-evidence"},
    {"std", 0ULL, "layout-evidence"},
    {"std::bad_alloc", 0ULL, "layout-evidence"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", 0ULL, "layout-evidence"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", 0ULL, "layout-evidence"},
    {"std::length_error", 0ULL, "layout-evidence"},
    {"std::logic_error", 0ULL, "layout-evidence"},
    {"std::out_of_range", 0ULL, "layout-evidence"},
    {"type_info", 0ULL, "layout-evidence"},
    {"wil", 0ULL, "layout-evidence"},
    {"wil::ResultException", 0ULL, "layout-evidence"},
    {"wil::StoredFailureInfo", 0ULL, "layout-evidence"},
    {"wil::details", 0ULL, "layout-evidence"},
    {"wil::details::in1diag3", 0ULL, "layout-evidence"},
    {"wil::details::shared_buffer", 0ULL, "layout-evidence"},
    {"wil::details_abi", 0ULL, "layout-evidence"},
    {"wil::details_abi::ProcessLocalStorageData<struct wil::details_abi::ProcessLocalData>", 0ULL, "layout-evidence"},
    {"wil::details_abi::SemaphoreValue", 0ULL, "layout-evidence"},
    {"wil::details_abi::ThreadLocalData", 0ULL, "layout-evidence"},
    {"wil::details_abi::ThreadLocalStorage<class wil::details::ThreadFailureCallbackHolder *>", 0ULL, "layout-evidence"},
    {"wil::details_abi::ThreadLocalStorage<struct wil::details_abi::ThreadLocalData>", 0ULL, "layout-evidence"},
    {"wil::unique_any_t<class wil::details::unique_storage<struct wil::details::handle_null_resource_policy<int (__cdecl *)(void *), int (__cdecl CloseHandle::*)(void *)> > >", 0ULL, "layout-evidence"},
    {"wistd::unique_ptr<struct _TOKEN_USER, struct wil::details::token_info_deleter>", 0ULL, "layout-evidence"},
    {"wistd::unique_ptr<unsigned short, struct wil::function_deleter<void * (__cdecl *)(void *), void * (__cdecl LocalFree::*)(void *)> >", 0ULL, "layout-evidence"},
    {"Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<2>, struct IWeakReference>", 32ULL, "allocation-size-evidence"},
    {"Microsoft::WRL::RuntimeClass<struct Windows::System::UserProfile::IDiagnosticsSettings>", 56ULL, "allocation-size-evidence"},
    {nullptr, 0, nullptr},
};
inline constexpr std::size_t type_count = (sizeof(types) / sizeof(types[0])) - 1;
inline constexpr FieldLayout fields[] = {
    {nullptr, nullptr, 0, 0, false},
};
inline constexpr std::size_t field_count = (sizeof(fields) / sizeof(fields[0])) - 1;
inline constexpr FieldObservation field_observations[] = {
    {"Microsoft::WRL::ActivationFactory<struct Microsoft::WRL::Implements<class Microsoft::WRL::FtmBase, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics>, class Microsoft::WRL::Details::Nil, class Microsoft::WRL::Details::Nil, 0>", nullptr, 0ULL, 8U, "read", 0x8CC0U, "?QueryInterface@?$ActivationFactory@U?$Implements@VFtmBase@WRL@Microsoft@@UIDiagnosticsSettingsStatics@UserProfile@System@Windows@@@WRL@Microsoft@@VNil@Details@23@V4523@$0A@@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAPEAX@Z", "likely"},
    {"Microsoft::WRL::ActivationFactory<struct Microsoft::WRL::Implements<class Microsoft::WRL::FtmBase, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics>, class Microsoft::WRL::Details::Nil, class Microsoft::WRL::Details::Nil, 0>", nullptr, 68ULL, 4U, "read-write", 0x8F60U, "?Release@?$ActivationFactory@U?$Implements@VFtmBase@WRL@Microsoft@@UIDiagnosticsSettingsStatics@UserProfile@System@Windows@@@WRL@Microsoft@@VNil@Details@23@V4523@$0A@@WRL@Microsoft@@UEAAKXZ", "likely"},
    {"Microsoft::WRL::ActivationFactory<struct Microsoft::WRL::Implements<class Microsoft::WRL::FtmBase, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics>, class Microsoft::WRL::Details::Nil, class Microsoft::WRL::Details::Nil, 0>", nullptr, 68ULL, 4U, "read", 0x8F60U, "?Release@?$ActivationFactory@U?$Implements@VFtmBase@WRL@Microsoft@@UIDiagnosticsSettingsStatics@UserProfile@System@Windows@@@WRL@Microsoft@@VNil@Details@23@V4523@$0A@@WRL@Microsoft@@UEAAKXZ", "likely"},
    {"Microsoft::WRL::ActivationFactory<struct Microsoft::WRL::Implements<class Microsoft::WRL::FtmBase, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics>, class Microsoft::WRL::Details::Nil, class Microsoft::WRL::Details::Nil, 0>", "TrustLevel", 80ULL, 8U, "read", 0x8390U, "?GetTrustLevel@?$ActivationFactory@U?$Implements@VFtmBase@WRL@Microsoft@@UIDiagnosticsSettingsStatics@UserProfile@System@Windows@@@WRL@Microsoft@@VNil@Details@23@V4523@$0A@@WRL@Microsoft@@UEAAJPEAW4TrustLevel@@@Z", "certain"},
    {"Microsoft::WRL::ActivationFactory<struct Microsoft::WRL::Implements<class Microsoft::WRL::FtmBase, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics>, class Microsoft::WRL::Details::Nil, class Microsoft::WRL::Details::Nil, 0>", nullptr, 88ULL, 4U, "read", 0x8F60U, "?Release@?$ActivationFactory@U?$Implements@VFtmBase@WRL@Microsoft@@UIDiagnosticsSettingsStatics@UserProfile@System@Windows@@@WRL@Microsoft@@VNil@Details@23@V4523@$0A@@WRL@Microsoft@@UEAAKXZ", "likely"},
    {"Microsoft::WRL::ComPtr<class Windows::System::UserProfile::DiagnosticsSettings>", nullptr, 0ULL, 8U, "read", 0x7890U, "??1?$ComPtr@VDiagnosticsSettings@UserProfile@System@Windows@@@WRL@Microsoft@@QEAA@XZ", "likely"},
    {"Microsoft::WRL::ComPtr<class Windows::System::UserProfile::DiagnosticsSettings>", nullptr, 0ULL, 8U, "read-write", 0x7890U, "??1?$ComPtr@VDiagnosticsSettings@UserProfile@System@Windows@@@WRL@Microsoft@@QEAA@XZ", "likely"},
    {"Microsoft::WRL::Details", nullptr, 0ULL, 8U, "read", 0x663CU, "?GetCacheEntry@Details@WRL@Microsoft@@YAJPEAVModuleBase@123@PEAIAEBU_GUID@@PEBUCreatorMap@123@PEAPEAUIUnknown@@@Z", "likely"},
    {"Microsoft::WRL::Details", nullptr, 0ULL, 8U, "read", 0x6898U, "?TerminateMap@Details@WRL@Microsoft@@YA_NPEAVModuleBase@123@PEBG_N@Z", "likely"},
    {"Microsoft::WRL::Details", nullptr, 0ULL, 1U, "read", 0x7100U, "??$CreateActivationFactory@VDiagnosticsSettingsFactory@UserProfile@System@Windows@@@Details@WRL@Microsoft@@YAJPEAIPEBUCreatorMap@012@AEBU_GUID@@PEAPEAUIUnknown@@@Z", "likely"},
    {"Microsoft::WRL::Details", nullptr, 0ULL, 4U, "read", 0x7100U, "??$CreateActivationFactory@VDiagnosticsSettingsFactory@UserProfile@System@Windows@@@Details@WRL@Microsoft@@YAJPEAIPEBUCreatorMap@012@AEBU_GUID@@PEAPEAUIUnknown@@@Z", "likely"},
    {"Microsoft::WRL::Details::MakeAllocator<class Windows::System::UserProfile::DiagnosticsSettings>", nullptr, 0ULL, 8U, "read", 0x78BCU, "??1?$MakeAllocator@VDiagnosticsSettings@UserProfile@System@Windows@@@Details@WRL@Microsoft@@QEAA@XZ", "likely"},
    {"Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::System::UserProfile::IDiagnosticsSettings>", nullptr, 16ULL, 8U, "read", 0x8AB0U, "?GetWeakReference@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@UIDiagnosticsSettings@UserProfile@System@Windows@@@Details@WRL@Microsoft@@UEAAJPEAPEAUIWeakReference@@@Z", "likely"},
    {"Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::System::UserProfile::IDiagnosticsSettings>", nullptr, 16ULL, 8U, "read-write", 0x8AB0U, "?GetWeakReference@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@UIDiagnosticsSettings@UserProfile@System@Windows@@@Details@WRL@Microsoft@@UEAAJPEAPEAUIWeakReference@@@Z", "likely"},
    {"Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::System::UserProfile::IDiagnosticsSettings>", nullptr, 24ULL, 8U, "read", 0x78DCU, "??1?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@UIDiagnosticsSettings@UserProfile@System@Windows@@@Details@WRL@Microsoft@@UEAA@XZ", "likely"},
    {"Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::System::UserProfile::IDiagnosticsSettings>", nullptr, 24ULL, 8U, "read", 0x9020U, "?Release@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@UIDiagnosticsSettings@UserProfile@System@Windows@@@Details@WRL@Microsoft@@UEAAKXZ", "likely"},
    {"Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::System::UserProfile::IDiagnosticsSettings>", nullptr, 24ULL, 8U, "read-write", 0x9020U, "?Release@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@UIDiagnosticsSettings@UserProfile@System@Windows@@@Details@WRL@Microsoft@@UEAAKXZ", "likely"},
    {"Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<2>, 1, 0, 0, struct IWeakReference>", nullptr, 0ULL, 8U, "read", 0x8E70U, "?QueryInterface@?$RuntimeClassImpl@U?$RuntimeClassFlags@$01@WRL@Microsoft@@$00$0A@$0A@UIWeakReference@@@Details@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAPEAX@Z", "likely"},
    {"Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<2>, 1, 0, 0, struct IWeakReference>", nullptr, 12ULL, 4U, "read-write", 0x7D00U, "?AddRef@?$RuntimeClassImpl@U?$RuntimeClassFlags@$01@WRL@Microsoft@@$00$0A@$0A@UIWeakReference@@@Details@WRL@Microsoft@@UEAAKXZ", "likely"},
    {"Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<2>, 1, 0, 0, struct IWeakReference>", nullptr, 12ULL, 4U, "read", 0x7D00U, "?AddRef@?$RuntimeClassImpl@U?$RuntimeClassFlags@$01@WRL@Microsoft@@$00$0A@$0A@UIWeakReference@@@Details@WRL@Microsoft@@UEAAKXZ", "likely"},
    {"Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<2>, 1, 0, 0, struct IWeakReference>", nullptr, 12ULL, 4U, "read-write", 0x90D0U, "?Release@?$RuntimeClassImpl@U?$RuntimeClassFlags@$01@WRL@Microsoft@@$00$0A@$0A@UIWeakReference@@@Details@WRL@Microsoft@@UEAAKXZ", "likely"},
    {"Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<2>, 1, 0, 0, struct IWeakReference>", nullptr, 12ULL, 4U, "read", 0x90D0U, "?Release@?$RuntimeClassImpl@U?$RuntimeClassFlags@$01@WRL@Microsoft@@$00$0A@$0A@UIWeakReference@@@Details@WRL@Microsoft@@UEAAKXZ", "likely"},
    {"Microsoft::WRL::Details::WeakReferenceImpl", nullptr, 0ULL, 8U, "write", 0x7B50U, "??_GWeakReferenceImpl@Details@WRL@Microsoft@@UEAAPEAXI@Z", "likely"},
    {"Microsoft::WRL::Details::WeakReferenceImpl", nullptr, 12ULL, 4U, "write", 0x7B50U, "??_GWeakReferenceImpl@Details@WRL@Microsoft@@UEAAPEAXI@Z", "likely"},
    {"Microsoft::WRL::Details::WeakReferenceImpl", nullptr, 16ULL, 4U, "write", 0x7B50U, "??_GWeakReferenceImpl@Details@WRL@Microsoft@@UEAAPEAXI@Z", "likely"},
    {"Microsoft::WRL::Details::WeakReferenceImpl", nullptr, 16ULL, 4U, "read-write", 0x91C0U, "?Resolve@WeakReferenceImpl@Details@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAPEAUIInspectable@@@Z", "likely"},
    {"Microsoft::WRL::Details::WeakReferenceImpl", nullptr, 16ULL, 4U, "read", 0x91C0U, "?Resolve@WeakReferenceImpl@Details@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAPEAUIInspectable@@@Z", "likely"},
    {"Microsoft::WRL::Details::WeakReferenceImpl", nullptr, 24ULL, 8U, "read", 0x91C0U, "?Resolve@WeakReferenceImpl@Details@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAPEAUIInspectable@@@Z", "likely"},
    {"Microsoft::WRL::FtmBase", nullptr, 24ULL, 8U, "read", 0x7DF0U, "?DisconnectObject@FtmBase@WRL@Microsoft@@UEAAJK@Z", "likely"},
    {"Microsoft::WRL::FtmBase", nullptr, 24ULL, 8U, "read", 0x8290U, "?GetMarshalSizeMax@FtmBase@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAXK1KPEAK@Z", "likely"},
    {"Microsoft::WRL::FtmBase", nullptr, 24ULL, 8U, "read", 0x8400U, "?GetUnmarshalClass@FtmBase@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAXK1KPEAU4@@Z", "likely"},
    {"Microsoft::WRL::FtmBase", nullptr, 24ULL, 8U, "read", 0x8C60U, "?MarshalInterface@FtmBase@WRL@Microsoft@@UEAAJPEAUIStream@@AEBU_GUID@@PEAXK2K@Z", "likely"},
    {"Microsoft::WRL::FtmBase", nullptr, 24ULL, 8U, "read", 0x9190U, "?ReleaseMarshalData@FtmBase@WRL@Microsoft@@UEAAJPEAUIStream@@@Z", "likely"},
    {"Microsoft::WRL::FtmBase", nullptr, 24ULL, 8U, "read", 0x92F0U, "?UnmarshalInterface@FtmBase@WRL@Microsoft@@UEAAJPEAUIStream@@AEBU_GUID@@PEAPEAX@Z", "likely"},
    {"Microsoft::WRL::Module<1, class Microsoft::WRL::Details::DefaultModule<1> >", nullptr, 0ULL, 8U, "write", 0x63B0U, "??_G?$Module@$00V?$DefaultModule@$00@Details@WRL@Microsoft@@@WRL@Microsoft@@UEAAPEAXI@Z", "likely"},
    {"Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<2>, struct IWeakReference>", nullptr, 12ULL, 4U, "write", 0x7A70U, "??_G?$RuntimeClass@U?$RuntimeClassFlags@$01@WRL@Microsoft@@UIWeakReference@@@WRL@Microsoft@@UEAAPEAXI@Z", "likely"},
    {"Microsoft::WRL::Wrappers::HString", nullptr, 0ULL, 8U, "read", 0x79C4U, "??1HString@Wrappers@WRL@Microsoft@@QEAA@XZ", "likely"},
    {"Microsoft::WRL::Wrappers::HString", nullptr, 0ULL, 8U, "read-write", 0x79C4U, "??1HString@Wrappers@WRL@Microsoft@@QEAA@XZ", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettings", nullptr, 24ULL, 8U, "read", 0x7C90U, "?AddRef@DiagnosticsSettings@UserProfile@System@Windows@@UEAAKXZ", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettings", nullptr, 24ULL, 8U, "read-write", 0x7C90U, "?AddRef@DiagnosticsSettings@UserProfile@System@Windows@@UEAAKXZ", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettings", nullptr, 32ULL, 8U, "read", 0x7AE0U, "??_GDiagnosticsSettings@UserProfile@System@Windows@@UEAAPEAXI@Z", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettings", nullptr, 32ULL, 8U, "read-write", 0x7AE0U, "??_GDiagnosticsSettings@UserProfile@System@Windows@@UEAAPEAXI@Z", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettings", nullptr, 32ULL, 8U, "read", 0x98C0U, "?get_CanUseDiagnosticsToTailorExperiences@DiagnosticsSettings@UserProfile@System@Windows@@UEAAJPEAE@Z", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettings", nullptr, 40ULL, 8U, "read", 0x7AE0U, "??_GDiagnosticsSettings@UserProfile@System@Windows@@UEAAPEAXI@Z", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettings", nullptr, 40ULL, 8U, "read-write", 0x7AE0U, "??_GDiagnosticsSettings@UserProfile@System@Windows@@UEAAPEAXI@Z", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettings", nullptr, 40ULL, 8U, "read", 0x9244U, "?RuntimeClassInitialize@DiagnosticsSettings@UserProfile@System@Windows@@QEAAJPEAUIUser@34@@Z", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettings", nullptr, 40ULL, 8U, "write", 0x9244U, "?RuntimeClassInitialize@DiagnosticsSettings@UserProfile@System@Windows@@QEAAJPEAUIUser@34@@Z", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettings", nullptr, 40ULL, 8U, "read", 0x9E20U, "?get_User@DiagnosticsSettings@UserProfile@System@Windows@@UEAAJPEAPEAUIUser@34@@Z", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettings", nullptr, 48ULL, 1U, "write", 0x845CU, "?GetUserSid@DiagnosticsSettings@UserProfile@System@Windows@@AEAAJPEAUIUser@34@AEAVHString@Wrappers@WRL@Microsoft@@@Z", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettings", nullptr, 48ULL, 1U, "write", 0x9244U, "?RuntimeClassInitialize@DiagnosticsSettings@UserProfile@System@Windows@@QEAAJPEAUIUser@34@@Z", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettings", nullptr, 48ULL, 1U, "read", 0x98C0U, "?get_CanUseDiagnosticsToTailorExperiences@DiagnosticsSettings@UserProfile@System@Windows@@UEAAJPEAE@Z", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettingsFactory", nullptr, 0ULL, 8U, "write", 0x7700U, "??0DiagnosticsSettingsFactory@UserProfile@System@Windows@@QEAA@XZ", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettingsFactory", nullptr, 8ULL, 8U, "write", 0x7700U, "??0DiagnosticsSettingsFactory@UserProfile@System@Windows@@QEAA@XZ", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettingsFactory", nullptr, 32ULL, 8U, "read-write", 0x7700U, "??0DiagnosticsSettingsFactory@UserProfile@System@Windows@@QEAA@XZ", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettingsFactory", nullptr, 32ULL, 8U, "read", 0x7A10U, "??_GDiagnosticsSettingsFactory@UserProfile@System@Windows@@UEAAPEAXI@Z", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettingsFactory", nullptr, 32ULL, 8U, "read-write", 0x7A10U, "??_GDiagnosticsSettingsFactory@UserProfile@System@Windows@@UEAAPEAXI@Z", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettingsFactory", nullptr, 40ULL, 8U, "write", 0x7700U, "??0DiagnosticsSettingsFactory@UserProfile@System@Windows@@QEAA@XZ", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettingsFactory", nullptr, 68ULL, 4U, "write", 0x7700U, "??0DiagnosticsSettingsFactory@UserProfile@System@Windows@@QEAA@XZ", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettingsFactory", nullptr, 68ULL, 4U, "write", 0x7A10U, "??_GDiagnosticsSettingsFactory@UserProfile@System@Windows@@UEAAPEAXI@Z", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettingsFactory", nullptr, 68ULL, 4U, "read-write", 0x7C10U, "?AddRef@DiagnosticsSettingsFactory@UserProfile@System@Windows@@UEAAKXZ", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettingsFactory", nullptr, 68ULL, 4U, "read", 0x7C10U, "?AddRef@DiagnosticsSettingsFactory@UserProfile@System@Windows@@UEAAKXZ", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettingsFactory", nullptr, 80ULL, 8U, "read-write", 0x7700U, "??0DiagnosticsSettingsFactory@UserProfile@System@Windows@@QEAA@XZ", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettingsFactory", nullptr, 88ULL, 4U, "write", 0x7700U, "??0DiagnosticsSettingsFactory@UserProfile@System@Windows@@QEAA@XZ", "likely"},
    {"Windows::System::UserProfile::DiagnosticsSettingsFactory", nullptr, 88ULL, 1U, "read", 0x7C10U, "?AddRef@DiagnosticsSettingsFactory@UserProfile@System@Windows@@UEAAKXZ", "likely"},
    {"std", nullptr, 8ULL, 2U, "write", 0x6F08U, "??$?HGU?$char_traits@G@std@@V?$allocator@G@1@@std@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@0@AEBV10@PEBG@Z", "likely"},
    {"std", nullptr, 24ULL, 8U, "write", 0x6F08U, "??$?HGU?$char_traits@G@std@@V?$allocator@G@1@@std@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@0@AEBV10@PEBG@Z", "likely"},
    {"std", nullptr, 32ULL, 8U, "write", 0x6F08U, "??$?HGU?$char_traits@G@std@@V?$allocator@G@1@@std@@YA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@0@AEBV10@PEBG@Z", "likely"},
    {"std::bad_alloc", nullptr, 0ULL, 8U, "write", 0x1340U, "??0bad_alloc@std@@QEAA@XZ", "likely"},
    {"std::bad_alloc", nullptr, 0ULL, 8U, "write", 0x7828U, "??0bad_alloc@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::bad_alloc", nullptr, 0ULL, 8U, "write", 0x7858U, "??0bad_alloc@std@@QEAA@PEBD@Z", "likely"},
    {"std::bad_alloc", nullptr, 0ULL, 8U, "write", 0x79F0U, "??1bad_alloc@std@@UEAA@XZ", "likely"},
    {"std::bad_alloc", nullptr, 0ULL, 8U, "write", 0x7B90U, "??_Gbad_alloc@std@@UEAAPEAXI@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 8ULL, 1U, "write", 0x1F48U, "??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 8ULL, 1U, "write", 0x1F80U, "??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAA@PEBD@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 8ULL, 8U, "read", 0x21C4U, "??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAA@XZ", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 8ULL, 1U, "write", 0x21C4U, "??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAA@XZ", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 8ULL, 8U, "read", 0x22D0U, "?_Copy@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@IEAAX_K0@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 8ULL, 8U, "read", 0x2610U, "?assign@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAAAEAV12@AEBV12@_K1@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 8ULL, 8U, "read", 0x2714U, "?assign@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAAAEAV12@PEBD_K@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 8ULL, 8U, "read", 0x280CU, "?erase@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAAAEAV12@_K0@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 24ULL, 8U, "read-write", 0x1F48U, "??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 24ULL, 8U, "write", 0x1F80U, "??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAA@PEBD@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 24ULL, 8U, "read-write", 0x21C4U, "??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAA@XZ", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 24ULL, 8U, "write", 0x22D0U, "?_Copy@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@IEAAX_K0@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 24ULL, 8U, "write", 0x24E8U, "?_Tidy@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@IEAAX_N_K@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 24ULL, 8U, "write", 0x2610U, "?assign@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAAAEAV12@AEBV12@_K1@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 24ULL, 8U, "read", 0x2714U, "?assign@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAAAEAV12@PEBD_K@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 24ULL, 8U, "write", 0x2714U, "?assign@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAAAEAV12@PEBD_K@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 24ULL, 8U, "read-write", 0x2714U, "?assign@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAAAEAV12@PEBD_K@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 24ULL, 8U, "read", 0x280CU, "?erase@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAAAEAV12@_K0@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 24ULL, 8U, "write", 0x280CU, "?erase@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAAAEAV12@_K0@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 32ULL, 8U, "write", 0x1F48U, "??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 32ULL, 8U, "write", 0x1F80U, "??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAA@PEBD@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 32ULL, 8U, "read", 0x21C4U, "??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAA@XZ", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 32ULL, 8U, "write", 0x21C4U, "??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAA@XZ", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 32ULL, 8U, "read", 0x22D0U, "?_Copy@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@IEAAX_K0@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 32ULL, 8U, "write", 0x22D0U, "?_Copy@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@IEAAX_K0@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 32ULL, 8U, "read", 0x24E8U, "?_Tidy@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@IEAAX_N_K@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 32ULL, 8U, "write", 0x24E8U, "?_Tidy@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@IEAAX_N_K@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 32ULL, 8U, "read", 0x2610U, "?assign@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAAAEAV12@AEBV12@_K1@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 32ULL, 8U, "read", 0x2714U, "?assign@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAAAEAV12@PEBD_K@Z", "likely"},
    {"std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>, class _STL70>", nullptr, 32ULL, 8U, "read", 0x280CU, "?erase@?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@std@@QEAAAEAV12@_K0@Z", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 8ULL, 2U, "write", 0x7614U, "??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@QEAA@PEBG@Z", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 8ULL, 8U, "read", 0x7904U, "??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@QEAA@XZ", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 8ULL, 2U, "write", 0x7904U, "??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@QEAA@XZ", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 8ULL, 8U, "read", 0x931CU, "?_Copy@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@IEAAX_K0@Z", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 8ULL, 8U, "read", 0x9598U, "?append@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@QEAAAEAV12@AEBV12@_K1@Z", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 8ULL, 8U, "read", 0x97ECU, "?erase@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@QEAAAEAV12@_K0@Z", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 24ULL, 8U, "write", 0x7614U, "??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@QEAA@PEBG@Z", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 24ULL, 8U, "write", 0x7904U, "??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@QEAA@XZ", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 24ULL, 8U, "write", 0x931CU, "?_Copy@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@IEAAX_K0@Z", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 24ULL, 8U, "write", 0x9518U, "?_Tidy@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@IEAAX_N_K@Z", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 24ULL, 8U, "read", 0x9598U, "?append@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@QEAAAEAV12@AEBV12@_K1@Z", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 24ULL, 8U, "write", 0x9598U, "?append@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@QEAAAEAV12@AEBV12@_K1@Z", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 24ULL, 8U, "read", 0x97ECU, "?erase@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@QEAAAEAV12@_K0@Z", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 24ULL, 8U, "write", 0x97ECU, "?erase@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@QEAAAEAV12@_K0@Z", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 32ULL, 8U, "write", 0x7614U, "??0?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@QEAA@PEBG@Z", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 32ULL, 8U, "read", 0x7904U, "??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@QEAA@XZ", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 32ULL, 8U, "write", 0x7904U, "??1?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@QEAA@XZ", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 32ULL, 8U, "read", 0x931CU, "?_Copy@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@IEAAX_K0@Z", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 32ULL, 8U, "write", 0x931CU, "?_Copy@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@IEAAX_K0@Z", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 32ULL, 8U, "read", 0x9518U, "?_Tidy@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@IEAAX_N_K@Z", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 32ULL, 8U, "write", 0x9518U, "?_Tidy@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@IEAAX_N_K@Z", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 32ULL, 8U, "read", 0x9598U, "?append@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@QEAAAEAV12@AEBV12@_K1@Z", "likely"},
    {"std::basic_string<unsigned short, struct std::char_traits<unsigned short>, class std::allocator<unsigned short>, class _STL70>", nullptr, 32ULL, 8U, "read", 0x97ECU, "?erase@?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@V_STL70@@@std@@QEAAAEAV12@_K0@Z", "likely"},
    {"std::length_error", nullptr, 0ULL, 8U, "write", 0x1FBCU, "??0length_error@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::length_error", nullptr, 0ULL, 8U, "write", 0x2030U, "??0length_error@std@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@1@@Z", "likely"},
    {"std::length_error", nullptr, 32ULL, 1U, "write", 0x1FBCU, "??0length_error@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::length_error", nullptr, 48ULL, 8U, "read-write", 0x1FBCU, "??0length_error@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::length_error", nullptr, 56ULL, 8U, "write", 0x1FBCU, "??0length_error@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::logic_error", nullptr, 0ULL, 8U, "write", 0x208CU, "??0logic_error@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::logic_error", nullptr, 32ULL, 1U, "write", 0x208CU, "??0logic_error@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::logic_error", nullptr, 32ULL, 8U, "read", 0x28B0U, "?what@logic_error@std@@UEBAPEBDXZ", "likely"},
    {"std::logic_error", nullptr, 48ULL, 8U, "read-write", 0x208CU, "??0logic_error@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::logic_error", nullptr, 56ULL, 8U, "write", 0x208CU, "??0logic_error@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::logic_error", nullptr, 56ULL, 8U, "read", 0x28B0U, "?what@logic_error@std@@UEBAPEBDXZ", "likely"},
    {"std::out_of_range", nullptr, 0ULL, 8U, "write", 0x20F4U, "??0out_of_range@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::out_of_range", nullptr, 0ULL, 8U, "write", 0x2168U, "??0out_of_range@std@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@V_STL70@@@1@PEAV_STL70@@@Z", "likely"},
    {"std::out_of_range", nullptr, 0ULL, 8U, "write", 0x2204U, "??1out_of_range@std@@UEAA@XZ", "likely"},
    {"std::out_of_range", nullptr, 0ULL, 8U, "write", 0x2260U, "??_Gout_of_range@std@@UEAAPEAXI@Z", "likely"},
    {"std::out_of_range", nullptr, 32ULL, 1U, "write", 0x20F4U, "??0out_of_range@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::out_of_range", nullptr, 32ULL, 8U, "read", 0x2204U, "??1out_of_range@std@@UEAA@XZ", "likely"},
    {"std::out_of_range", nullptr, 32ULL, 1U, "write", 0x2204U, "??1out_of_range@std@@UEAA@XZ", "likely"},
    {"std::out_of_range", nullptr, 32ULL, 8U, "read", 0x2260U, "??_Gout_of_range@std@@UEAAPEAXI@Z", "likely"},
    {"std::out_of_range", nullptr, 32ULL, 1U, "write", 0x2260U, "??_Gout_of_range@std@@UEAAPEAXI@Z", "likely"},
    {"std::out_of_range", nullptr, 48ULL, 8U, "read-write", 0x20F4U, "??0out_of_range@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::out_of_range", nullptr, 48ULL, 8U, "read-write", 0x2204U, "??1out_of_range@std@@UEAA@XZ", "likely"},
    {"std::out_of_range", nullptr, 48ULL, 8U, "read-write", 0x2260U, "??_Gout_of_range@std@@UEAAPEAXI@Z", "likely"},
    {"std::out_of_range", nullptr, 56ULL, 8U, "write", 0x20F4U, "??0out_of_range@std@@QEAA@AEBV01@@Z", "likely"},
    {"std::out_of_range", nullptr, 56ULL, 8U, "read", 0x2204U, "??1out_of_range@std@@UEAA@XZ", "likely"},
    {"std::out_of_range", nullptr, 56ULL, 8U, "write", 0x2204U, "??1out_of_range@std@@UEAA@XZ", "likely"},
    {"std::out_of_range", nullptr, 56ULL, 8U, "read", 0x2260U, "??_Gout_of_range@std@@UEAAPEAXI@Z", "likely"},
    {"std::out_of_range", nullptr, 56ULL, 8U, "write", 0x2260U, "??_Gout_of_range@std@@UEAAPEAXI@Z", "likely"},
    {"wil", nullptr, 0ULL, 2U, "read", 0x3F14U, "?GetFailureLogString@wil@@YAJPEAG_KAEBUFailureInfo@1@@Z", "likely"},
    {"wil::ResultException", nullptr, 0ULL, 8U, "write", 0x349CU, "??0ResultException@wil@@QEAA@AEBUFailureInfo@1@@Z", "likely"},
    {"wil::ResultException", nullptr, 0ULL, 8U, "write", 0x3504U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::ResultException", nullptr, 24ULL, 16U, "write", 0x3504U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::ResultException", nullptr, 40ULL, 16U, "write", 0x3504U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::ResultException", nullptr, 56ULL, 16U, "write", 0x3504U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::ResultException", nullptr, 72ULL, 16U, "write", 0x3504U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::ResultException", nullptr, 88ULL, 16U, "write", 0x3504U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::ResultException", nullptr, 104ULL, 16U, "write", 0x3504U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::ResultException", nullptr, 120ULL, 16U, "write", 0x3504U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::ResultException", nullptr, 176ULL, 8U, "read-write", 0x349CU, "??0ResultException@wil@@QEAA@AEBUFailureInfo@1@@Z", "likely"},
    {"wil::ResultException", nullptr, 176ULL, 8U, "write", 0x3504U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::ResultException", nullptr, 184ULL, 8U, "read-write", 0x349CU, "??0ResultException@wil@@QEAA@AEBUFailureInfo@1@@Z", "likely"},
    {"wil::ResultException", nullptr, 184ULL, 8U, "write", 0x3504U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::ResultException", nullptr, 192ULL, 8U, "read-write", 0x349CU, "??0ResultException@wil@@QEAA@AEBUFailureInfo@1@@Z", "likely"},
    {"wil::ResultException", nullptr, 192ULL, 8U, "write", 0x3504U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::ResultException", nullptr, 192ULL, 8U, "read", 0x3704U, "??1ResultException@wil@@UEAA@XZ", "likely"},
    {"wil::ResultException", nullptr, 192ULL, 8U, "read-write", 0x3704U, "??1ResultException@wil@@UEAA@XZ", "likely"},
    {"wil::ResultException", nullptr, 200ULL, 8U, "read-write", 0x349CU, "??0ResultException@wil@@QEAA@AEBUFailureInfo@1@@Z", "likely"},
    {"wil::ResultException", nullptr, 200ULL, 8U, "write", 0x3504U, "??0ResultException@wil@@QEAA@AEBV01@@Z", "likely"},
    {"wil::ResultException", nullptr, 200ULL, 8U, "read-write", 0x3704U, "??1ResultException@wil@@UEAA@XZ", "likely"},
    {"wil::StoredFailureInfo", nullptr, 0ULL, 16U, "write", 0x5584U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::StoredFailureInfo", nullptr, 16ULL, 16U, "write", 0x5584U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::StoredFailureInfo", nullptr, 32ULL, 16U, "write", 0x5584U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::StoredFailureInfo", nullptr, 48ULL, 16U, "write", 0x5584U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::StoredFailureInfo", nullptr, 64ULL, 16U, "write", 0x5584U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::StoredFailureInfo", nullptr, 80ULL, 16U, "write", 0x5584U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::StoredFailureInfo", nullptr, 96ULL, 16U, "write", 0x5584U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::StoredFailureInfo", nullptr, 152ULL, 8U, "read", 0x37F0U, "??1StoredFailureInfo@wil@@QEAA@XZ", "likely"},
    {"wil::StoredFailureInfo", nullptr, 152ULL, 8U, "read-write", 0x37F0U, "??1StoredFailureInfo@wil@@QEAA@XZ", "likely"},
    {"wil::StoredFailureInfo", nullptr, 152ULL, 8U, "read", 0x5584U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::StoredFailureInfo", nullptr, 152ULL, 8U, "write", 0x5584U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::StoredFailureInfo", nullptr, 152ULL, 8U, "read", 0x5584U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::StoredFailureInfo", nullptr, 160ULL, 8U, "read-write", 0x37F0U, "??1StoredFailureInfo@wil@@QEAA@XZ", "likely"},
    {"wil::StoredFailureInfo", nullptr, 160ULL, 8U, "read", 0x5584U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::StoredFailureInfo", nullptr, 160ULL, 8U, "write", 0x5584U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::StoredFailureInfo", nullptr, 160ULL, 8U, "read", 0x5584U, "?SetFailureInfo@StoredFailureInfo@wil@@QEAAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 0ULL, 2U, "write", 0x4C1CU, "?LogStringPrintf@details@wil@@YAPEAGPEAGPEBG1ZZ", "likely"},
    {"wil::details", nullptr, 0ULL, 1U, "read", 0x4F70U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 0ULL, 4U, "write", 0x53B0U, "?ResultFromCaughtExceptionInternal@details@wil@@YA?AUResultStatus@12@PEAG_KPEA_N@Z", "likely"},
    {"wil::details", nullptr, 4ULL, 1U, "read", 0x3D50U, "?GetContextAndNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@PEAD_K@Z", "likely"},
    {"wil::details", nullptr, 4ULL, 4U, "read-write", 0x4F70U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 4ULL, 4U, "write", 0x53B0U, "?ResultFromCaughtExceptionInternal@details@wil@@YA?AUResultStatus@12@PEAG_KPEA_N@Z", "likely"},
    {"wil::details", nullptr, 8ULL, 4U, "read", 0x4F70U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 8ULL, 4U, "write", 0x53B0U, "?ResultFromCaughtExceptionInternal@details@wil@@YA?AUResultStatus@12@PEAG_KPEA_N@Z", "likely"},
    {"wil::details", nullptr, 8ULL, 4U, "read", 0x5FECU, "?WilFailFast@details@wil@@YAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 16ULL, 4U, "write", 0x4F70U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 24ULL, 8U, "read", 0x4F70U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 56ULL, 8U, "read", 0x4F70U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 64ULL, 2U, "read", 0x4F70U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 64ULL, 4U, "read", 0x5FECU, "?WilFailFast@details@wil@@YAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 72ULL, 8U, "write", 0x3D50U, "?GetContextAndNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@PEAD_K@Z", "likely"},
    {"wil::details", nullptr, 128ULL, 8U, "read", 0x4F70U, "?MicrosoftInternalNotifyFailure@details@wil@@YAXPEAUFailureInfo@2@@Z", "likely"},
    {"wil::details", nullptr, 136ULL, 8U, "read", 0x5FECU, "?WilFailFast@details@wil@@YAXAEBUFailureInfo@2@@Z", "likely"},
    {"wil::details::shared_buffer", nullptr, 0ULL, 8U, "read", 0x60F4U, "?create@shared_buffer@details@wil@@QEAA_N_K@Z", "likely"},
    {"wil::details::shared_buffer", nullptr, 0ULL, 8U, "read-write", 0x60F4U, "?create@shared_buffer@details@wil@@QEAA_N_K@Z", "likely"},
    {"wil::details::shared_buffer", nullptr, 0ULL, 8U, "read", 0x60F4U, "?create@shared_buffer@details@wil@@QEAA_N_K@Z", "likely"},
    {"wil::details::shared_buffer", nullptr, 0ULL, 8U, "write", 0x60F4U, "?create@shared_buffer@details@wil@@QEAA_N_K@Z", "likely"},
    {"wil::details::shared_buffer", nullptr, 8ULL, 8U, "read-write", 0x60F4U, "?create@shared_buffer@details@wil@@QEAA_N_K@Z", "likely"},
    {"wil::details::shared_buffer", nullptr, 8ULL, 8U, "write", 0x60F4U, "?create@shared_buffer@details@wil@@QEAA_N_K@Z", "likely"},
    {"wil::details_abi::ProcessLocalStorageData<struct wil::details_abi::ProcessLocalData>", nullptr, 0ULL, 4U, "read", 0x5214U, "?Release@?$ProcessLocalStorageData@UProcessLocalData@details_abi@wil@@@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ProcessLocalStorageData<struct wil::details_abi::ProcessLocalData>", nullptr, 0ULL, 4U, "write", 0x5214U, "?Release@?$ProcessLocalStorageData@UProcessLocalData@details_abi@wil@@@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ProcessLocalStorageData<struct wil::details_abi::ProcessLocalData>", nullptr, 0ULL, 4U, "read", 0x5214U, "?Release@?$ProcessLocalStorageData@UProcessLocalData@details_abi@wil@@@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ProcessLocalStorageData<struct wil::details_abi::ProcessLocalData>", nullptr, 0ULL, 4U, "write", 0x5214U, "?Release@?$ProcessLocalStorageData@UProcessLocalData@details_abi@wil@@@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ProcessLocalStorageData<struct wil::details_abi::ProcessLocalData>", nullptr, 0ULL, 4U, "read", 0x5214U, "?Release@?$ProcessLocalStorageData@UProcessLocalData@details_abi@wil@@@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::ProcessLocalStorageData<struct wil::details_abi::ProcessLocalData>", nullptr, 8ULL, 8U, "read", 0x5214U, "?Release@?$ProcessLocalStorageData@UProcessLocalData@details_abi@wil@@@details_abi@wil@@QEAAXXZ", "likely"},
    {"wil::details_abi::SemaphoreValue", nullptr, 0ULL, 8U, "read", 0x3788U, "??1SemaphoreValue@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::SemaphoreValue", nullptr, 8ULL, 8U, "read", 0x3788U, "??1SemaphoreValue@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 8ULL, 8U, "read", 0x58DCU, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 16ULL, 4U, "read", 0x58DCU, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 24ULL, 8U, "read", 0x3860U, "??1ThreadLocalData@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 24ULL, 8U, "write", 0x3860U, "??1ThreadLocalData@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 24ULL, 8U, "read", 0x58DCU, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 24ULL, 8U, "write", 0x58DCU, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 24ULL, 8U, "read", 0x58DCU, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 32ULL, 2U, "read", 0x3860U, "??1ThreadLocalData@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 32ULL, 4U, "write", 0x3860U, "??1ThreadLocalData@details_abi@wil@@QEAA@XZ", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 32ULL, 4U, "write", 0x58DCU, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 32ULL, 2U, "read", 0x58DCU, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 34ULL, 2U, "read", 0x58DCU, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::details_abi::ThreadLocalData", nullptr, 34ULL, 2U, "write", 0x58DCU, "?SetLastError@ThreadLocalData@details_abi@wil@@QEAAXAEBUFailureInfo@3@@Z", "likely"},
    {"wil::unique_any_t<class wil::details::unique_storage<struct wil::details::handle_null_resource_policy<int (__cdecl *)(void *), int (__cdecl CloseHandle::*)(void *)> > >", nullptr, 0ULL, 8U, "read", 0x7948U, "??1?$unique_any_t@V?$unique_storage@U?$handle_null_resource_policy@P6AHPEAX@Z$1?CloseHandle@@YAH0@Z@details@wil@@@details@wil@@@wil@@QEAA@XZ", "likely"},
    {"wistd::unique_ptr<struct _TOKEN_USER, struct wil::details::token_info_deleter>", nullptr, 0ULL, 8U, "read", 0x79A0U, "??1?$unique_ptr@U_TOKEN_USER@@Utoken_info_deleter@details@wil@@@wistd@@QEAA@XZ", "likely"},
    {"wistd::unique_ptr<struct _TOKEN_USER, struct wil::details::token_info_deleter>", nullptr, 0ULL, 8U, "read-write", 0x79A0U, "??1?$unique_ptr@U_TOKEN_USER@@Utoken_info_deleter@details@wil@@@wistd@@QEAA@XZ", "likely"},
    {"wistd::unique_ptr<unsigned short, struct wil::function_deleter<void * (__cdecl *)(void *), void * (__cdecl LocalFree::*)(void *)> >", nullptr, 0ULL, 8U, "read", 0x7974U, "??1?$unique_ptr@GU?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@QEAA@XZ", "likely"},
    {"wistd::unique_ptr<unsigned short, struct wil::function_deleter<void * (__cdecl *)(void *), void * (__cdecl LocalFree::*)(void *)> >", nullptr, 0ULL, 8U, "read-write", 0x7974U, "??1?$unique_ptr@GU?$function_deleter@P6APEAXPEAX@Z$1?LocalFree@@YAPEAX0@Z@wil@@@wistd@@QEAA@XZ", "likely"},
    {nullptr, nullptr, 0, 0, nullptr, 0, nullptr, nullptr},
};
inline constexpr std::size_t field_observation_count = (sizeof(field_observations) / sizeof(field_observations[0])) - 1;
inline constexpr BaseLayout bases[] = {
    {nullptr, nullptr, -1, false, nullptr, nullptr},
};
inline constexpr std::size_t base_count = (sizeof(bases) / sizeof(bases[0])) - 1;
inline constexpr VTableLayout vtables[] = {
    {"const type_info::`vftable'", 0xD000U, 1U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const std::logic_error::`vftable'", 0xD018U, 3U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const std::length_error::`vftable'", 0xD030U, 3U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const std::out_of_range::`vftable'", 0xD048U, 3U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const wil::ResultException::`vftable'", 0xD1A8U, 2U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::Details::DefaultModule<1>::`vftable'", 0xD258U, 12U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const std::bad_alloc::`vftable'", 0xD2B8U, 3U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Microsoft::WRL::RuntimeClassFlags<2>, struct IWeakReference>::`vftable'", 0xD2D0U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::Details::WeakReferenceImpl::`vftable'", 0xD2F8U, 5U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::FtmBase::`vftable'", 0xD320U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Windows::System::UserProfile::IDiagnosticsSettings>::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct IWeakReferenceSource>'}", 0xD368U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::RuntimeClass<struct Windows::System::UserProfile::IDiagnosticsSettings>::`vftable'{for `Windows::System::UserProfile::IDiagnosticsSettings'}", 0xD388U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::ActivationFactory<struct Microsoft::WRL::Implements<class Microsoft::WRL::FtmBase, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics>, class Microsoft::WRL::Details::Nil, class Microsoft::WRL::Details::Nil, 0>::`vftable'{for `Microsoft::WRL::Details::Selector<struct Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics>, struct Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Microsoft::WRL::Details::ImplementsMarker<class Microsoft::WRL::FtmBase>, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics> >'}", 0xD3D0U, 8U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::ActivationFactory<struct Microsoft::WRL::Implements<class Microsoft::WRL::FtmBase, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics>, class Microsoft::WRL::Details::Nil, class Microsoft::WRL::Details::Nil, 0>::`vftable'{for `Microsoft::WRL::Details::Selector<class Microsoft::WRL::FtmBase, struct Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Microsoft::WRL::Details::ImplementsMarker<class Microsoft::WRL::FtmBase>, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics> >'}", 0xD410U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Microsoft::WRL::ActivationFactory<struct Microsoft::WRL::Implements<class Microsoft::WRL::FtmBase, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics>, class Microsoft::WRL::Details::Nil, class Microsoft::WRL::Details::Nil, 0>::`vftable'", 0xD458U, 11U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Windows::System::UserProfile::DiagnosticsSettingsFactory::`vftable'{for `Microsoft::WRL::Details::Selector<struct Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics>, struct Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Microsoft::WRL::Details::ImplementsMarker<class Microsoft::WRL::FtmBase>, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics> >'}", 0xD4C0U, 8U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Windows::System::UserProfile::DiagnosticsSettingsFactory::`vftable'{for `Microsoft::WRL::Details::Selector<class Microsoft::WRL::FtmBase, struct Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct Microsoft::WRL::Details::ImplementsMarker<class Microsoft::WRL::FtmBase>, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics> >'}", 0xD500U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Windows::System::UserProfile::DiagnosticsSettingsFactory::`vftable'", 0xD548U, 8U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Windows::System::UserProfile::DiagnosticsSettings::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, struct IWeakReferenceSource>'}", 0xD588U, 4U, "msvc-??_7-plus-pe-rdata", "likely"},
    {"const Windows::System::UserProfile::DiagnosticsSettings::`vftable'{for `Windows::System::UserProfile::IDiagnosticsSettings'}", 0xD5A8U, 9U, "msvc-??_7-plus-pe-rdata", "likely"},
    {nullptr, 0, 0, nullptr, nullptr},
};
inline constexpr std::size_t vtable_count = (sizeof(vtables) / sizeof(vtables[0])) - 1;
inline constexpr VTableSlotLayout vtable_slots[] = {
    {0xD000U, 0U, 0x19D0U, nullptr, nullptr, true, 0},
    {0xD018U, 0U, 0x2260U, nullptr, nullptr, true, 0},
    {0xD018U, 1U, 0x28B0U, "?what@logic_error@std@@UEBAPEBDXZ", "public: virtual char const * __cdecl std::logic_error::what(void) const", false, 0},
    {0xD018U, 2U, 0x2470U, "?_Doraise@logic_error@std@@MEBAXXZ", "protected: virtual void __cdecl std::logic_error::_Doraise(void) const", false, 0},
    {0xD030U, 0U, 0x2260U, nullptr, nullptr, true, 0},
    {0xD030U, 1U, 0x28B0U, nullptr, nullptr, true, 0},
    {0xD030U, 2U, 0x2430U, "?_Doraise@length_error@std@@MEBAXXZ", "protected: virtual void __cdecl std::length_error::_Doraise(void) const", false, 0},
    {0xD048U, 0U, 0x2260U, nullptr, nullptr, true, 0},
    {0xD048U, 1U, 0x28B0U, nullptr, nullptr, true, 0},
    {0xD048U, 2U, 0x24B0U, "?_Doraise@out_of_range@std@@MEBAXXZ", "protected: virtual void __cdecl std::out_of_range::_Doraise(void) const", false, 0},
    {0xD1A8U, 0U, 0x3920U, nullptr, nullptr, true, 0},
    {0xD1A8U, 1U, 0x6270U, "?what@ResultException@wil@@UEBAPEBDXZ", "public: virtual char const * __cdecl wil::ResultException::what(void) const", false, 0},
    {0xD258U, 0U, 0x63B0U, nullptr, nullptr, true, 0},
    {0xD258U, 1U, 0x6850U, "?IncrementObjectCount@?$Module@$00V?$DefaultModule@$00@Details@WRL@Microsoft@@@WRL@Microsoft@@UEAAKXZ", "public: virtual unsigned long __cdecl Microsoft::WRL::Module<1, class Microsoft::WRL::Details::DefaultModule<1> >::IncrementObjectCount(void)", false, 0},
    {0xD258U, 2U, 0x6410U, "?DecrementObjectCount@?$Module@$00V?$DefaultModule@$00@Details@WRL@Microsoft@@@WRL@Microsoft@@UEAAKXZ", "public: virtual unsigned long __cdecl Microsoft::WRL::Module<1, class Microsoft::WRL::Details::DefaultModule<1> >::DecrementObjectCount(void)", false, 0},
    {0xD258U, 3U, 0x6840U, nullptr, nullptr, true, 0},
    {0xD258U, 4U, 0x6800U, nullptr, nullptr, true, 0},
    {0xD258U, 5U, 0x6830U, nullptr, nullptr, true, 0},
    {0xD258U, 6U, 0x6810U, nullptr, nullptr, true, 0},
    {0xD258U, 7U, 0x6820U, nullptr, nullptr, true, 0},
    {0xD258U, 8U, 0x6870U, nullptr, nullptr, true, 0},
    {0xD258U, 9U, 0x6870U, nullptr, nullptr, true, 0},
    {0xD258U, 10U, 0x6870U, nullptr, nullptr, true, 0},
    {0xD258U, 11U, 0x6870U, nullptr, nullptr, true, 0},
    {0xD2B8U, 0U, 0x7B90U, nullptr, nullptr, true, 0},
    {0xD2B8U, 1U, 0x1A20U, nullptr, nullptr, true, 0},
    {0xD2B8U, 2U, 0x94C0U, "?_Doraise@bad_alloc@std@@MEBAXXZ", "protected: virtual void __cdecl std::bad_alloc::_Doraise(void) const", false, 0},
    {0xD2D0U, 0U, 0x8E70U, nullptr, nullptr, true, 0},
    {0xD2D0U, 1U, 0x7D00U, nullptr, nullptr, true, 0},
    {0xD2D0U, 2U, 0x90D0U, nullptr, nullptr, true, 0},
    {0xD2D0U, 3U, 0x28D0U, nullptr, nullptr, true, 0},
    {0xD2D0U, 4U, 0x7A70U, nullptr, nullptr, true, 0},
    {0xD2F8U, 0U, 0x8E70U, nullptr, nullptr, true, 0},
    {0xD2F8U, 1U, 0x7D00U, nullptr, nullptr, true, 0},
    {0xD2F8U, 2U, 0x90D0U, nullptr, nullptr, true, 0},
    {0xD2F8U, 3U, 0x91C0U, "?Resolve@WeakReferenceImpl@Details@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAPEAUIInspectable@@@Z", "public: virtual long __cdecl Microsoft::WRL::Details::WeakReferenceImpl::Resolve(struct _GUID const &, struct IInspectable * *)", false, 0},
    {0xD2F8U, 4U, 0x7B50U, nullptr, nullptr, true, 0},
    {0xD320U, 0U, 0x28D0U, nullptr, nullptr, true, 0},
    {0xD320U, 1U, 0x28D0U, nullptr, nullptr, true, 0},
    {0xD320U, 2U, 0x28D0U, nullptr, nullptr, true, 0},
    {0xD320U, 3U, 0x8400U, "?GetUnmarshalClass@FtmBase@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAXK1KPEAU4@@Z", "public: virtual long __cdecl Microsoft::WRL::FtmBase::GetUnmarshalClass(struct _GUID const &, void *, unsigned long, void *, unsigned long, struct _GUID *)", false, 0},
    {0xD320U, 4U, 0x8290U, "?GetMarshalSizeMax@FtmBase@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAXK1KPEAK@Z", "public: virtual long __cdecl Microsoft::WRL::FtmBase::GetMarshalSizeMax(struct _GUID const &, void *, unsigned long, void *, unsigned long, unsigned long *)", false, 0},
    {0xD320U, 5U, 0x8C60U, "?MarshalInterface@FtmBase@WRL@Microsoft@@UEAAJPEAUIStream@@AEBU_GUID@@PEAXK2K@Z", "public: virtual long __cdecl Microsoft::WRL::FtmBase::MarshalInterface(struct IStream *, struct _GUID const &, void *, unsigned long, void *, unsigned long)", false, 0},
    {0xD320U, 6U, 0x92F0U, "?UnmarshalInterface@FtmBase@WRL@Microsoft@@UEAAJPEAUIStream@@AEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl Microsoft::WRL::FtmBase::UnmarshalInterface(struct IStream *, struct _GUID const &, void * *)", false, 0},
    {0xD320U, 7U, 0x9190U, "?ReleaseMarshalData@FtmBase@WRL@Microsoft@@UEAAJPEAUIStream@@@Z", "public: virtual long __cdecl Microsoft::WRL::FtmBase::ReleaseMarshalData(struct IStream *)", false, 0},
    {0xD320U, 8U, 0x7DF0U, "?DisconnectObject@FtmBase@WRL@Microsoft@@UEAAJK@Z", "public: virtual long __cdecl Microsoft::WRL::FtmBase::DisconnectObject(unsigned long)", false, 0},
    {0xD368U, 0U, 0x8E60U, nullptr, nullptr, true, 0},
    {0xD368U, 1U, 0x7CF0U, nullptr, nullptr, true, 0},
    {0xD368U, 2U, 0x90C0U, nullptr, nullptr, true, 0},
    {0xD368U, 3U, 0x8AB0U, "?GetWeakReference@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@UIDiagnosticsSettings@UserProfile@System@Windows@@@Details@WRL@Microsoft@@UEAAJPEAPEAUIWeakReference@@@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::System::UserProfile::IDiagnosticsSettings>::GetWeakReference(struct IWeakReference * *)", false, 0},
    {0xD388U, 0U, 0x8D80U, "?QueryInterface@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@UIDiagnosticsSettings@UserProfile@System@Windows@@@Details@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::System::UserProfile::IDiagnosticsSettings>::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0xD388U, 1U, 0x7C90U, "?AddRef@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@UIDiagnosticsSettings@UserProfile@System@Windows@@@Details@WRL@Microsoft@@UEAAKXZ", "public: virtual unsigned long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::System::UserProfile::IDiagnosticsSettings>::AddRef(void)", false, 0},
    {0xD388U, 2U, 0x9020U, "?Release@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@UIDiagnosticsSettings@UserProfile@System@Windows@@@Details@WRL@Microsoft@@UEAAKXZ", "public: virtual unsigned long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::System::UserProfile::IDiagnosticsSettings>::Release(void)", false, 0},
    {0xD388U, 3U, 0x81F0U, "?GetIids@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@UIDiagnosticsSettings@UserProfile@System@Windows@@@Details@WRL@Microsoft@@UEAAJPEAKPEAPEAU_GUID@@@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::System::UserProfile::IDiagnosticsSettings>::GetIids(unsigned long *, struct _GUID * *)", false, 0},
    {0xD388U, 4U, 0x7BE0U, "?GetRuntimeClassName@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@UIDiagnosticsSettings@UserProfile@System@Windows@@@Details@WRL@Microsoft@@UEAAJPEAPEAUHSTRING__@@@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::System::UserProfile::IDiagnosticsSettings>::GetRuntimeClassName(struct HSTRING__* *)", false, 0},
    {0xD388U, 5U, 0x6870U, "?GetTrustLevel@?$RuntimeClassImpl@U?$RuntimeClassFlags@$00@WRL@Microsoft@@$00$00$0A@UIDiagnosticsSettings@UserProfile@System@Windows@@@Details@WRL@Microsoft@@UEAAJPEAW4TrustLevel@@@Z", "public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<1>, 1, 1, 0, struct Windows::System::UserProfile::IDiagnosticsSettings>::GetTrustLevel(enum TrustLevel *)", false, 0},
    {0xD388U, 6U, 0x28D0U, nullptr, nullptr, true, 0},
    {0xD388U, 7U, 0x28D0U, nullptr, nullptr, true, 0},
    {0xD388U, 8U, 0x7AA0U, nullptr, nullptr, true, 0},
    {0xD3D0U, 0U, 0x8D70U, nullptr, nullptr, true, 0},
    {0xD3D0U, 1U, 0x7C80U, nullptr, nullptr, true, 0},
    {0xD3D0U, 2U, 0x9010U, nullptr, nullptr, true, 0},
    {0xD3D0U, 3U, 0x81E0U, nullptr, nullptr, true, 0},
    {0xD3D0U, 4U, 0x8320U, nullptr, nullptr, true, 0},
    {0xD3D0U, 5U, 0x83D0U, nullptr, nullptr, true, 0},
    {0xD3D0U, 6U, 0x28D0U, nullptr, nullptr, true, 0},
    {0xD3D0U, 7U, 0x28D0U, nullptr, nullptr, true, 0},
    {0xD410U, 0U, 0x8D60U, nullptr, nullptr, true, 0},
    {0xD410U, 1U, 0x7C70U, nullptr, nullptr, true, 0},
    {0xD410U, 2U, 0x9000U, nullptr, nullptr, true, 0},
    {0xD410U, 3U, 0x8400U, nullptr, nullptr, true, 0},
    {0xD410U, 4U, 0x8290U, nullptr, nullptr, true, 0},
    {0xD410U, 5U, 0x8C60U, nullptr, nullptr, true, 0},
    {0xD410U, 6U, 0x92F0U, nullptr, nullptr, true, 0},
    {0xD410U, 7U, 0x9190U, nullptr, nullptr, true, 0},
    {0xD410U, 8U, 0x7DF0U, nullptr, nullptr, true, 0},
    {0xD458U, 0U, 0x8CC0U, "?QueryInterface@?$ActivationFactory@U?$Implements@VFtmBase@WRL@Microsoft@@UIDiagnosticsSettingsStatics@UserProfile@System@Windows@@@WRL@Microsoft@@VNil@Details@23@V4523@$0A@@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl Microsoft::WRL::ActivationFactory<struct Microsoft::WRL::Implements<class Microsoft::WRL::FtmBase, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics>, class Microsoft::WRL::Details::Nil, class Microsoft::WRL::Details::Nil, 0>::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0xD458U, 1U, 0x7C10U, "?AddRef@?$ActivationFactory@U?$Implements@VFtmBase@WRL@Microsoft@@UIDiagnosticsSettingsStatics@UserProfile@System@Windows@@@WRL@Microsoft@@VNil@Details@23@V4523@$0A@@WRL@Microsoft@@UEAAKXZ", "public: virtual unsigned long __cdecl Microsoft::WRL::ActivationFactory<struct Microsoft::WRL::Implements<class Microsoft::WRL::FtmBase, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics>, class Microsoft::WRL::Details::Nil, class Microsoft::WRL::Details::Nil, 0>::AddRef(void)", false, 0},
    {0xD458U, 2U, 0x8F60U, "?Release@?$ActivationFactory@U?$Implements@VFtmBase@WRL@Microsoft@@UIDiagnosticsSettingsStatics@UserProfile@System@Windows@@@WRL@Microsoft@@VNil@Details@23@V4523@$0A@@WRL@Microsoft@@UEAAKXZ", "public: virtual unsigned long __cdecl Microsoft::WRL::ActivationFactory<struct Microsoft::WRL::Implements<class Microsoft::WRL::FtmBase, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics>, class Microsoft::WRL::Details::Nil, class Microsoft::WRL::Details::Nil, 0>::Release(void)", false, 0},
    {0xD458U, 3U, 0x8170U, "?GetIids@?$ActivationFactory@U?$Implements@VFtmBase@WRL@Microsoft@@UIDiagnosticsSettingsStatics@UserProfile@System@Windows@@@WRL@Microsoft@@VNil@Details@23@V4523@$0A@@WRL@Microsoft@@UEAAJPEAKPEAPEAU_GUID@@@Z", "public: virtual long __cdecl Microsoft::WRL::ActivationFactory<struct Microsoft::WRL::Implements<class Microsoft::WRL::FtmBase, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics>, class Microsoft::WRL::Details::Nil, class Microsoft::WRL::Details::Nil, 0>::GetIids(unsigned long *, struct _GUID * *)", false, 0},
    {0xD458U, 4U, 0x82F0U, "?GetRuntimeClassName@?$ActivationFactory@U?$Implements@VFtmBase@WRL@Microsoft@@UIDiagnosticsSettingsStatics@UserProfile@System@Windows@@@WRL@Microsoft@@VNil@Details@23@V4523@$0A@@WRL@Microsoft@@UEAAJPEAPEAUHSTRING__@@@Z", "public: virtual long __cdecl Microsoft::WRL::ActivationFactory<struct Microsoft::WRL::Implements<class Microsoft::WRL::FtmBase, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics>, class Microsoft::WRL::Details::Nil, class Microsoft::WRL::Details::Nil, 0>::GetRuntimeClassName(struct HSTRING__* *)", false, 0},
    {0xD458U, 5U, 0x8390U, "?GetTrustLevel@?$ActivationFactory@U?$Implements@VFtmBase@WRL@Microsoft@@UIDiagnosticsSettingsStatics@UserProfile@System@Windows@@@WRL@Microsoft@@VNil@Details@23@V4523@$0A@@WRL@Microsoft@@UEAAJPEAW4TrustLevel@@@Z", "public: virtual long __cdecl Microsoft::WRL::ActivationFactory<struct Microsoft::WRL::Implements<class Microsoft::WRL::FtmBase, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics>, class Microsoft::WRL::Details::Nil, class Microsoft::WRL::Details::Nil, 0>::GetTrustLevel(enum TrustLevel *)", false, 0},
    {0xD458U, 6U, 0x7BE0U, "?ActivateInstance@?$ActivationFactory@U?$Implements@VFtmBase@WRL@Microsoft@@UIDiagnosticsSettingsStatics@UserProfile@System@Windows@@@WRL@Microsoft@@VNil@Details@23@V4523@$0A@@WRL@Microsoft@@UEAAJPEAPEAUIInspectable@@@Z", "public: virtual long __cdecl Microsoft::WRL::ActivationFactory<struct Microsoft::WRL::Implements<class Microsoft::WRL::FtmBase, struct Windows::System::UserProfile::IDiagnosticsSettingsStatics>, class Microsoft::WRL::Details::Nil, class Microsoft::WRL::Details::Nil, 0>::ActivateInstance(struct IInspectable * *)", false, 0},
    {0xD458U, 7U, 0x7A10U, nullptr, nullptr, true, 0},
    {0xD458U, 8U, 0x7100U, nullptr, nullptr, true, 0},
    {0xD458U, 9U, 0x8C20U, nullptr, nullptr, true, 0},
    {0xD458U, 10U, 0x8C30U, nullptr, nullptr, true, 0},
    {0xD4C0U, 0U, 0x8F30U, nullptr, nullptr, true, 0},
    {0xD4C0U, 1U, 0x7C80U, nullptr, nullptr, true, 0},
    {0xD4C0U, 2U, 0x9180U, nullptr, nullptr, true, 0},
    {0xD4C0U, 3U, 0x8280U, nullptr, nullptr, true, 0},
    {0xD4C0U, 4U, 0x8380U, nullptr, nullptr, true, 0},
    {0xD4C0U, 5U, 0x83F0U, nullptr, nullptr, true, 0},
    {0xD4C0U, 6U, 0x7E20U, "?GetDefault@DiagnosticsSettingsFactory@UserProfile@System@Windows@@UEAAJPEAPEAUIDiagnosticsSettings@234@@Z", "public: virtual long __cdecl Windows::System::UserProfile::DiagnosticsSettingsFactory::GetDefault(struct Windows::System::UserProfile::IDiagnosticsSettings * *)", false, 0},
    {0xD4C0U, 7U, 0x7FE0U, "?GetForUser@DiagnosticsSettingsFactory@UserProfile@System@Windows@@UEAAJPEAUIUser@34@PEAPEAUIDiagnosticsSettings@234@@Z", "public: virtual long __cdecl Windows::System::UserProfile::DiagnosticsSettingsFactory::GetForUser(struct Windows::System::IUser *, struct Windows::System::UserProfile::IDiagnosticsSettings * *)", false, 0},
    {0xD500U, 0U, 0x8F20U, nullptr, nullptr, true, 0},
    {0xD500U, 1U, 0x7C70U, nullptr, nullptr, true, 0},
    {0xD500U, 2U, 0x9170U, nullptr, nullptr, true, 0},
    {0xD500U, 3U, 0x8400U, nullptr, nullptr, true, 0},
    {0xD500U, 4U, 0x8290U, nullptr, nullptr, true, 0},
    {0xD500U, 5U, 0x8C60U, nullptr, nullptr, true, 0},
    {0xD500U, 6U, 0x92F0U, nullptr, nullptr, true, 0},
    {0xD500U, 7U, 0x9190U, nullptr, nullptr, true, 0},
    {0xD500U, 8U, 0x7DF0U, nullptr, nullptr, true, 0},
    {0xD548U, 0U, 0x8F10U, "?QueryInterface@DiagnosticsSettingsFactory@UserProfile@System@Windows@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl Windows::System::UserProfile::DiagnosticsSettingsFactory::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0xD548U, 1U, 0x7C10U, "?AddRef@DiagnosticsSettingsFactory@UserProfile@System@Windows@@UEAAKXZ", "public: virtual unsigned long __cdecl Windows::System::UserProfile::DiagnosticsSettingsFactory::AddRef(void)", false, 0},
    {0xD548U, 2U, 0x9160U, "?Release@DiagnosticsSettingsFactory@UserProfile@System@Windows@@UEAAKXZ", "public: virtual unsigned long __cdecl Windows::System::UserProfile::DiagnosticsSettingsFactory::Release(void)", false, 0},
    {0xD548U, 3U, 0x8270U, "?GetIids@DiagnosticsSettingsFactory@UserProfile@System@Windows@@UEAAJPEAKPEAPEAU_GUID@@@Z", "public: virtual long __cdecl Windows::System::UserProfile::DiagnosticsSettingsFactory::GetIids(unsigned long *, struct _GUID * *)", false, 0},
    {0xD548U, 4U, 0x8360U, "?GetRuntimeClassName@DiagnosticsSettingsFactory@UserProfile@System@Windows@@UEAAJPEAPEAUHSTRING__@@@Z", "public: virtual long __cdecl Windows::System::UserProfile::DiagnosticsSettingsFactory::GetRuntimeClassName(struct HSTRING__* *)", false, 0},
    {0xD548U, 5U, 0x83E0U, "?GetTrustLevel@DiagnosticsSettingsFactory@UserProfile@System@Windows@@UEAAJPEAW4TrustLevel@@@Z", "public: virtual long __cdecl Windows::System::UserProfile::DiagnosticsSettingsFactory::GetTrustLevel(enum TrustLevel *)", false, 0},
    {0xD548U, 6U, 0x7BE0U, nullptr, nullptr, true, 0},
    {0xD548U, 7U, 0x7A10U, nullptr, nullptr, true, 0},
    {0xD588U, 0U, 0x8F00U, nullptr, nullptr, true, 0},
    {0xD588U, 1U, 0x7CF0U, nullptr, nullptr, true, 0},
    {0xD588U, 2U, 0x9150U, nullptr, nullptr, true, 0},
    {0xD588U, 3U, 0x8AB0U, nullptr, nullptr, true, 0},
    {0xD5A8U, 0U, 0x8EF0U, "?QueryInterface@DiagnosticsSettings@UserProfile@System@Windows@@UEAAJAEBU_GUID@@PEAPEAX@Z", "public: virtual long __cdecl Windows::System::UserProfile::DiagnosticsSettings::QueryInterface(struct _GUID const &, void * *)", false, 0},
    {0xD5A8U, 1U, 0x7C90U, "?AddRef@DiagnosticsSettings@UserProfile@System@Windows@@UEAAKXZ", "public: virtual unsigned long __cdecl Windows::System::UserProfile::DiagnosticsSettings::AddRef(void)", false, 0},
    {0xD5A8U, 2U, 0x9140U, "?Release@DiagnosticsSettings@UserProfile@System@Windows@@UEAAKXZ", "public: virtual unsigned long __cdecl Windows::System::UserProfile::DiagnosticsSettings::Release(void)", false, 0},
    {0xD5A8U, 3U, 0x8260U, "?GetIids@DiagnosticsSettings@UserProfile@System@Windows@@UEAAJPEAKPEAPEAU_GUID@@@Z", "public: virtual long __cdecl Windows::System::UserProfile::DiagnosticsSettings::GetIids(unsigned long *, struct _GUID * *)", false, 0},
    {0xD5A8U, 4U, 0x8330U, "?GetRuntimeClassName@DiagnosticsSettings@UserProfile@System@Windows@@UEAAJPEAPEAUHSTRING__@@@Z", "public: virtual long __cdecl Windows::System::UserProfile::DiagnosticsSettings::GetRuntimeClassName(struct HSTRING__* *)", false, 0},
    {0xD5A8U, 5U, 0x83E0U, "?GetTrustLevel@DiagnosticsSettings@UserProfile@System@Windows@@UEAAJPEAW4TrustLevel@@@Z", "public: virtual long __cdecl Windows::System::UserProfile::DiagnosticsSettings::GetTrustLevel(enum TrustLevel *)", false, 0},
    {0xD5A8U, 6U, 0x98C0U, "?get_CanUseDiagnosticsToTailorExperiences@DiagnosticsSettings@UserProfile@System@Windows@@UEAAJPEAE@Z", "public: virtual long __cdecl Windows::System::UserProfile::DiagnosticsSettings::get_CanUseDiagnosticsToTailorExperiences(unsigned char *)", false, 0},
    {0xD5A8U, 7U, 0x9E20U, "?get_User@DiagnosticsSettings@UserProfile@System@Windows@@UEAAJPEAPEAUIUser@34@@Z", "public: virtual long __cdecl Windows::System::UserProfile::DiagnosticsSettings::get_User(struct Windows::System::IUser * *)", false, 0},
    {0xD5A8U, 8U, 0x7AE0U, nullptr, nullptr, true, 0},
    {0, 0, 0, nullptr, nullptr, true, 0},
};
inline constexpr std::size_t vtable_slot_count = (sizeof(vtable_slots) / sizeof(vtable_slots[0])) - 1;
}
